[package]
name = "methods"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.risc0]
methods = ["guest"]

[dev-dependencies]
risc0-zkvm = { version = "0.20.1" }

[build-dependencies]
risc0-build = { version = "0.20.1" }