[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
serde = {version = "1.0", features = ["derive"]}
risc0-zkvm = { version = "=0.19.0" }
num-bigint = { version = "0.4.4", features = ["rand"] }
rand_chacha = "0.3.1"
num-traits = "0.2.17"